// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3NqjU4HMuhn4vhtjTqyhS126neo-g-mM',
    appId: '1:208915178959:web:d3315631757dd5e8b2deba',
    messagingSenderId: '208915178959',
    projectId: 'charity-fb784',
    authDomain: 'charity-fb784.firebaseapp.com',
    storageBucket: 'charity-fb784.firebasestorage.app',
    measurementId: 'G-HR1Q68Q4JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarjUtsYOoQ9gjK6SCEHG1pSIaqvrHYjw',
    appId: '1:208915178959:android:705a738aa371714bb2deba',
    messagingSenderId: '208915178959',
    projectId: 'charity-fb784',
    storageBucket: 'charity-fb784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCUG7ZLB92VjfIFaRjrIjpe1irhQy-9Fc',
    appId: '1:208915178959:ios:bb08e6640f20b3a0b2deba',
    messagingSenderId: '208915178959',
    projectId: 'charity-fb784',
    storageBucket: 'charity-fb784.firebasestorage.app',
    iosBundleId: 'com.example.charity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCUG7ZLB92VjfIFaRjrIjpe1irhQy-9Fc',
    appId: '1:208915178959:ios:bb08e6640f20b3a0b2deba',
    messagingSenderId: '208915178959',
    projectId: 'charity-fb784',
    storageBucket: 'charity-fb784.firebasestorage.app',
    iosBundleId: 'com.example.charity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3NqjU4HMuhn4vhtjTqyhS126neo-g-mM',
    appId: '1:208915178959:web:69f0a030be1836b2b2deba',
    messagingSenderId: '208915178959',
    projectId: 'charity-fb784',
    authDomain: 'charity-fb784.firebaseapp.com',
    storageBucket: 'charity-fb784.firebasestorage.app',
    measurementId: 'G-3SJBCWKWQV',
  );
}
